# Generated by Django 5.0.3 on 2024-04-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='ml',
            field=models.IntegerField(default=50),
        ),
    ]
