# Generated by Django 5.0.3 on 2024-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_size_ml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category2',
            name='detail_cat2',
        ),
        migrations.RemoveField(
            model_name='category2',
            name='gender',
        ),
        migrations.AddField(
            model_name='category2',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='DetailCategory2',
        ),
    ]
