# Generated by Django 5.0.3 on 2024-06-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_back_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='back_image',
            field=models.ImageField(null=True, upload_to='ai_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
