# Generated by Django 5.0.3 on 2024-06-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_back_image_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='back_image',
        ),
    ]
