# Generated by Django 5.0.3 on 2024-04-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_item_image_item_back_image_item_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='image',
        ),
    ]
