# Generated by Django 5.0.3 on 2024-06-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_item_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='back_image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
