# Generated by Django 5.0.3 on 2024-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_back_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='media/'),
        ),
    ]
