# Generated by Django 5.0.4 on 2024-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_rename_item_image_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
