# Generated by Django 5.0.4 on 2024-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_item_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='like',
            field=models.ManyToManyField(related_name='liked_by', to='item.item'),
        ),
        migrations.DeleteModel(
            name='item_like',
        ),
    ]
