# Generated by Django 5.0.4 on 2024-06-05 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_item_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item_like',
            new_name='Itemlike',
        ),
    ]
