# Generated by Django 5.0.4 on 2024-06-17 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150)),
                ('month', models.DateField()),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.category1')),
                ('category2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.category2')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(choices=[(0, '신청 완료'), (1, '상품 선별 중'), (2, '상품 제공 완료')], default=0)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.delivery')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.keyword')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.subscribe')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribePayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=50, null=True)),
                ('tid', models.CharField(max_length=50)),
                ('cid', models.CharField(max_length=50)),
                ('sid', models.CharField(max_length=30, null=True)),
                ('partner_order_id', models.CharField(max_length=150, null=True)),
                ('partner_user_id', models.CharField(max_length=150, null=True)),
                ('payment_method_type', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(default='prepared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('next_payment_date', models.DateTimeField(null=True)),
                ('payment_interval', models.IntegerField(default=30)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
