# Generated by Django 5.0.3 on 2024-05-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_rename_item_image_item_image'),
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.category2'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
