# Generated by Django 5.0.3 on 2024-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_keyword_category2_subscribe_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='state',
            field=models.IntegerField(choices=[(0, '신청 완료'), (1, '상품 선별 중'), (2, '상품 제공 완료')], default=0),
        ),
    ]
