# Generated by Django 5.0.3 on 2024-06-03 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_rename_item_image_item_image'),
        ('subscribe', '0003_alter_subscribe_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
