# Generated by Django 5.0.3 on 2024-06-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_coupon_usercoupon'),
        ('subscribe', '0004_subscribe_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.delivery'),
        ),
    ]
