# Generated by Django 5.0.3 on 2024-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0007_alter_subscribepayinfo_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribepayinfo',
            name='aid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscribepayinfo',
            name='next_payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscribepayinfo',
            name='partner_order_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subscribepayinfo',
            name='partner_user_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subscribepayinfo',
            name='payment_interval',
            field=models.IntegerField(default=30),
        ),
    ]
