# Generated by Django 5.0.3 on 2024-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_subscribepayinfo_aid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribepayinfo',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
