# Generated by Django 5.0.4 on 2024-06-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tale',
        ),
    ]
