# Generated by Django 5.0.4 on 2024-06-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_delete_tale'),
        ('guide', '0002_scentcategory_alter_scentnote_name_and_more'),
    ]

    operations = [
    ]
