# Generated by Django 5.0.4 on 2024-04-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_ordercart_is_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_number', models.CharField(max_length=10)),
                ('coupon_discount_rate', models.IntegerField()),
                ('coupon_use', models.BooleanField()),
                ('coupon_expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.BooleanField()),
                ('receiver', models.CharField(max_length=30)),
                ('receiver_address', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=11)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('cart_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_time', models.DateTimeField()),
                ('card_number', models.CharField(max_length=16)),
                ('card_expire_date', models.DateField()),
                ('card_owner', models.CharField(max_length=30)),
                ('card_cvc', models.CharField(max_length=3)),
                ('cart_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('coupon_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.coupon')),
                ('delivery_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.delivery')),
            ],
        ),
    ]
