# Generated by Django 5.0.3 on 2024-04-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('receiver', models.CharField(max_length=30)),
                ('receiver_address', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
