# Generated by Django 5.0.3 on 2024-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_delivery_receiver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='receiver_detailAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='receiver_extraAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='receiver_postcode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='receiver_address',
            field=models.TextField(null=True),
        ),
    ]
