# Generated by Django 5.0.3 on 2024-06-13 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_coupon_usercoupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=50, null=True)),
                ('tid', models.CharField(max_length=50)),
                ('cid', models.CharField(max_length=50)),
                ('partner_order_id', models.CharField(max_length=150, null=True)),
                ('partner_user_id', models.CharField(max_length=150, null=True)),
                ('payment_method_type', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(default='prepared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
