# Generated by Django 5.0.3 on 2024-06-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayInfo',
        ),
    ]
