# Generated by Django 5.0.4 on 2024-06-17 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=6, null=True)),
                ('address', models.TextField(null=True)),
                ('detailAddress', models.CharField(max_length=100, null=True)),
                ('extraAddress', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('profile_img', models.URLField(default=' ', null=True)),
                ('membership', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
