# Generated by Django 5.0.3 on 2024-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddinfo',
            name='profile_img',
            field=models.URLField(default=' ', null=True),
        ),
    ]
