# Generated by Django 5.0.3 on 2024-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_useraddinfo_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddinfo',
            name='user_name',
            field=models.CharField(default='ooo', max_length=50),
        ),
    ]
