# Generated by Django 5.0.4 on 2024-05-07 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Franding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age_range', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
                ('cat1', models.CharField(max_length=100)),
                ('cat2', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
