# Generated by Django 5.0.3 on 2024-04-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_ordercart_is_review'),
        ('review', '0002_review_datetime_review_ordercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='orderCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.ordercart'),
        ),
    ]
