# Generated by Django 5.0.3 on 2024-04-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_ordercart_is_review'),
        ('review', '0003_alter_review_ordercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='orderCart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.ordercart'),
        ),
    ]
