# Generated by Django 5.0.3 on 2024-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_cart_ordercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
