# Generated by Django 5.0.3 on 2024-06-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_delivery_info_alter_cart_status'),
        ('payment', '0004_coupon_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.usercoupon'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('ordercart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.ordercart')),
            ],
        ),
    ]
