# Generated by Django 5.0.3 on 2024-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_user_coupon_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
